version: "3.8"

services:
  backend:
    build: ./backend
    container_name: django_backend
    restart: always
    env_file: ./backend/.env.postgres
    volumes:
      - ./backend:/app-back
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: react_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - ./backend/.env.postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data: